version: "3.9"
networks:
  dev:
    driver: bridge
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - dev
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: InspectorGadget
      POSTGRES_HOST: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: